services:
  # Build and run the application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-release-stage
    image: avawing/alluvial-app
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    user: nonroot:nonroot
    command: ["/docker-gs-ping"]

    networks:
      - prometheus-golang
    volumes:
      - .:/app
  run-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: run-test-stage
    command: ["go", "test", "-v", "./..."]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - prometheus-golang

networks:
  prometheus-golang:

volumes:
  prometheus_data:

  # Run tests in a separate container

