apiVersion: v1
kind: Service
metadata:
  name: alluvial-app-service
spec:
  selector:
    app: alluvial-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  externalIPs:
    - 192.168.49.2 # external IP from minikube

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alluvial-app
spec:
  selector:
    matchLabels:
      app: alluvial-app
  replicas: 3
  template:
    metadata:
      labels:
        app: alluvial-app
    spec:
      containers:
        - name: alluvial-app
          image: avawing/alluvial-app        # Make sure this matches your built Go image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          command: ["/docker-gs-ping"]